#!/bin/bash
set -e

# Define variables
VENV_DIR=/opt/kalinka/venv
SCRIPT_DIR=/usr/bin
STARTUP_SCRIPT=/etc/systemd/system/kalinka.service
USER=kalusr

echo Create a system user
adduser --system --no-create-home --group $USER
usermod -aG audio $USER
mkhomedir_helper $USER

USER_HOME=$(sudo -u "$USER" sh -c 'echo $HOME')

mkdir -p $USER_HOME/.local/share/kalinka
chown $USER:$USER -R $USER_HOME/.local/share/kalinka

echo Creating and activating virtual environment
python3 -m venv $VENV_DIR

# Install necessary Python packages in the virtual environment
source $VENV_DIR/bin/activate
pip install httpx[http2] pydantic fastapi uvicorn zeroconf pyyaml pybind11
deactivate

chown -R $USER:$USER /opt/kalinka/*

# Reload systemd and enable the service
systemctl daemon-reload
systemctl enable kalinka.service
systemctl restart kalinka.service

echo "Installation complete. The script will run at startup."