"""
Version information for the Kalinka server.

Two distinct, unrelated versions live here:

* The **package version** (:func:`get_version`) is generated by setuptools_scm
  from the ``kalinka-v*`` git tag and written to ``_version.py`` at build time.
* The **REST/WS API version** (:data:`REST_API_VERSION` /
  :func:`get_rest_api_version`) is the client-facing HTTP/WebSocket contract
  version. It is hardcoded and bumped by hand when that API changes — it is not
  derived from git or the package version. It is exposed via ``/server/version``
  and mDNS discovery so clients (e.g. the frontend app) can check compatibility.
  (Distinct from ``kalinka_plugin_sdk.__version__``, which the plugins'
  ``REQUIRES_SDK`` specifiers gate the server↔plugin contract on.)
"""

# Written by setuptools_scm at build time; absent only in an unbuilt source tree.
try:
    from ._version import version as __version__
except ImportError:
    __version__ = None


def get_version() -> str:
    """Return the package version (``X.Y.Z`` or a ``X.Y.Z.devN+…`` dev form).

    Comes from ``_version.py`` (setuptools_scm / the ``kalinka-v*`` tag). Falls
    back to ``"0.0.0"`` only when run from a source tree that was never built.
    """
    if __version__ and __version__ != "0.0.0+unknown":
        return __version__
    return "0.0.0"


# Client-facing REST/WebSocket API contract version. Bump deliberately when the
# client API changes; independent of the package version above. Distinct from
# kalinka_plugin_sdk.__version__ (the server<->plugin SDK contract).
# 0.2: playback moved to renderers — output selection lives behind /renderer/*,
# and the built-in local-alsa device is gone.
# 0.3: /queue/ws reports the renderer topology — renderers_changed and
# current_renderer_changed events, and the matching replay state fields.
# 0.4: playback state carries the output device (audio_info.output) and the
# device volume names the backend it is applied by.
# 0.5: renderer records say whether this Core can drive them (compatible)
# and whether they can install a release of themselves (upgrade_supported),
# which POST /renderer/{id}/upgrade asks them to do; playback state names
# the URL the renderer is fetching (stream_url).
# 0.6: search is asked one source at a time — `sources` is required on
# /search/matches and /ai_search, /ai_search takes a single source and no
# longer pages, and module records name the optional calls they answer
# (capabilities).
REST_API_VERSION = "0.6"


def get_rest_api_version() -> str:
    """Return the client-facing REST/WS API version (see :data:`REST_API_VERSION`)."""
    return REST_API_VERSION
